export type TaskTier = 'petty' | 'sinister' | 'diabolical' | 'legendary';
export type TaskCategory = 'schemes' | 'heists' | 'research' | 'mayhem';
export type TaskStatus = 'queued' | 'in-progress' | 'complete';
export type QueueTarget = TaskCategory;

export interface TaskTemplate {
  name: string;
  description: string;
  category: TaskCategory;
  tier: TaskTier;
}

export interface Task {
  id: string;
  template: TaskTemplate;
  status: TaskStatus;
  tier: TaskTier;
  goldReward: number;
  clicksRequired: number;
  clicksRemaining: number;
  assignedMinionId: string | null;
  queuedAt: number;
  isSpecialOp?: boolean;
  specialOpExpiry?: number;
  isScoutTask?: boolean;
  assignedQueue: QueueTarget | null;
  /** true = operation generated by a scheme (doesn't cost budget) */
  isOperation?: boolean;
  /** Scheme metadata — stored on task so operations can be generated after routing */
  schemeTargetDept?: TaskCategory;
  schemeOperationCount?: number;
  schemeOperationTiers?: TaskTier[];
  /** Combo mult inherited from generating scheme (added to gold mult on operation completion) */
  comboMult?: number;
}

// ─── Scheme card system ─────────────────────

export interface SchemeCard {
  id: string;                    // unique per card in deck
  templateId: string;            // references a TaskTemplate name
  tier: TaskTier;
  targetDept: TaskCategory;      // which execution dept gets the operations
  operationCount: number;        // 1-3 operations generated on completion
  operationTiers: TaskTier[];    // pre-rolled tiers for each operation
  clicksRequired: number;        // from SCHEME_TIER_CONFIG
  directGold: number;            // small baseline gold on scheme completion
  isSpecialOp?: boolean;         // 15% chance, +1 mult on operations
}

/** Operation count distributions for each scheme tier */
export const SCHEME_OP_DISTRIBUTIONS: Record<TaskTier, { count: number; weight: number }[]> = {
  petty:      [{ count: 1, weight: 60 }, { count: 2, weight: 40 }],
  sinister:   [{ count: 1, weight: 40 }, { count: 2, weight: 40 }, { count: 3, weight: 20 }],
  diabolical: [{ count: 2, weight: 50 }, { count: 3, weight: 50 }],
  legendary:  [{ count: 3, weight: 100 }],
};

export const SCHEME_TIER_CONFIG: Record<TaskTier, { clicks: number; directGold: number }> = {
  petty:      { clicks: 3,  directGold: 3 },
  sinister:   { clicks: 5,  directGold: 7 },
  diabolical: { clicks: 8,  directGold: 15 },
  legendary:  { clicks: 12, directGold: 30 },
};

/** Roll operation count from the tier's distribution */
export function rollOperationCount(tier: TaskTier): number {
  const dist = SCHEME_OP_DISTRIBUTIONS[tier];
  const totalWeight = dist.reduce((a, d) => a + d.weight, 0);
  let roll = Math.random() * totalWeight;
  for (const { count, weight } of dist) {
    roll -= weight;
    if (roll <= 0) return count;
  }
  return dist[dist.length - 1].count;
}

// ─── Combo system (scheme fishing depth) ─────────────────────

export interface ComboState {
  deptFocus: { dept: TaskCategory | null; count: number };
  tierLadder: { lastTier: TaskTier | null; step: number };
}

export function createDefaultComboState(): ComboState {
  return {
    deptFocus: { dept: null, count: 0 },
    tierLadder: { lastTier: null, step: 0 },
  };
}

export const TIER_INDEX: Record<TaskTier, number> = {
  petty: 0, sinister: 1, diabolical: 2, legendary: 3,
};

export const DEPT_FOCUS_CAP = 4;

export const TIER_ESCALATION_BONUS: Record<number, number> = {
  1: 0, 2: 2, 3: 5, 4: 10,
};

/** Dept focus bonus: count-1 capped at DEPT_FOCUS_CAP, 0 for count ≤ 1 */
export function getDeptFocusBonus(count: number): number {
  if (count <= 1) return 0;
  return Math.min(count - 1, DEPT_FOCUS_CAP);
}

/** Tier escalation bonus from step lookup, capped at step 4 */
export function getTierEscalationBonus(step: number): number {
  if (step <= 1) return 0;
  return TIER_ESCALATION_BONUS[Math.min(step, 4)] ?? 0;
}

/** Advance combo state after executing a scheme. Returns new state + bonus breakdown. */
export function advanceComboState(
  state: ComboState,
  targetDept: TaskCategory,
  schemeTier: TaskTier,
): { newState: ComboState; deptFocusBonus: number; tierEscalationBonus: number; totalComboMult: number } {
  // Dept focus track
  let focusCount: number;
  if (state.deptFocus.dept === targetDept) {
    focusCount = state.deptFocus.count + 1;
  } else {
    focusCount = 1;
  }

  // Tier ladder track
  let ladderStep: number;
  const currentIndex = TIER_INDEX[schemeTier];
  const lastIndex = state.tierLadder.lastTier !== null ? TIER_INDEX[state.tierLadder.lastTier] : -1;

  if (lastIndex >= 0 && currentIndex === lastIndex + 1) {
    ladderStep = state.tierLadder.step + 1;
  } else {
    ladderStep = 1;
  }

  const deptFocusBonus = getDeptFocusBonus(focusCount);
  const tierEscalationBonus = getTierEscalationBonus(ladderStep);

  return {
    newState: {
      deptFocus: { dept: targetDept, count: focusCount },
      tierLadder: { lastTier: schemeTier, step: ladderStep },
    },
    deptFocusBonus,
    tierEscalationBonus,
    totalComboMult: deptFocusBonus + tierEscalationBonus,
  };
}

/** Preview combo bonus without mutating state (for UI badges). */
export function previewComboBonus(
  state: ComboState,
  targetDept: TaskCategory,
  schemeTier: TaskTier,
): { deptFocusBonus: number; tierEscalationBonus: number; totalComboMult: number } {
  const { deptFocusBonus, tierEscalationBonus, totalComboMult } = advanceComboState(state, targetDept, schemeTier);
  return { deptFocusBonus, tierEscalationBonus, totalComboMult };
}

export const TIER_CONFIG: Record<TaskTier, { gold: number; clicks: number }> = {
  petty: { gold: 2, clicks: 10 },
  sinister: { gold: 5, clicks: 18 },
  diabolical: { gold: 12, clicks: 30 },
  legendary: { gold: 30, clicks: 45 },
};

/** Cost to unlock a tier in a department */
export const TIER_UNLOCK_COSTS: Record<TaskTier, number> = {
  petty: 0,       // always free
  sinister: 15,
  diabolical: 80,
  legendary: 300,
};

/** Default scouting tier weights (within unlocked tiers) */
export const SCOUTING_TIER_WEIGHTS: Record<TaskTier, number> = {
  petty: 50,
  sinister: 30,
  diabolical: 15,
  legendary: 5,
};
